### ISSUE TITLE
Feature request: hide (not just disable) unused features

### ISSUE THREAD

**Issue by danallan** [c9/c9.ide.run.debug#1]
Currently, the features object will disable buttons in the debugger UI if that feature does not exist. However, it might make more sense to hide the corresponding feature altogether.

For example, "setBreakBehavior" is not relevant in languages without exceptions and is therefore "false" in the features object, but the button still appears in the UI with a disabled state. I think it would reduce confusion to hide it altogether.

**Comment by nightwing** [comment]
this is fixed now
