### ISSUE TITLE
Editing a watch expression sometimes edits the wrong one

### ISSUE THREAD

**Issue by octachrome** [c9/c9.ide.run.debug#21]
This issue occurs when the debugger is stopped. Editing a watch and changing the expression causes the expression of a different watch to be changed instead of the one you were editing.
- Open the debugger pane, and ensure that you are not debugging.
- Add a watch expression, `a`.
- Add a watch expression, `b`.
- Double-click on expression `b`, and change it to `c`.

Expected: you are left with expressions `a` and `c`.
Actual: you are left with expressions `b` and `c` -- `a` has been incorrectly changed.

**Comment by nightwing** [comment]
fix for this is in a pull request now

**Comment by octachrome** [comment]
@nightwing Awesome, thanks.
