### ISSUE TITLE
gdbdebugger.setState() does not set value

### ISSUE THREAD

**Issue by xoob** [c9/c9.ide.run.debug#6]
@danallan Found a small bug in the GDB debugger I wanted to let you know about.

Calling `gdbdebugger.setState()` does not update the `state` variable correctly, since both the argument and the private variable have the same name:

``` javascript
var state;

function setState(state) {
    state = state;
    emit("stateChange", {state: state});
}
```

https://github.com/c9/c9.ide.run.debug/blob/0c1f549611827c01e467861f95742d289faf25a0/debuggers/gdb/gdbdebugger.js#L201

**Comment by danallan** [comment]
Thanks, @xoob !! Addressed in pull request #7
