### ISSUE TITLE
Package C9 link broken

### ISSUE THREAD

**Issue by serkanserttop** [c9/c9.ide.run.debug#9]
It is not related only to this package, but many other c9 packages' links also return 500 http error. (mentioned in the main README.md)
https://c9.io/packages/c9.ide.run.debug

They also do not appear in https://c9.io/packages
Were these links working at all, or is this a temporary error?
(Sorry I opened the issue with the wrong account previously)

**Comment by nightwing** [comment]
There are no package pages for default c9 packages so far, since they are not meant to be installed separately.
Where is the https://c9.io/packages/c9.ide.run.debug link mentioned?

**Comment by serkanserttop** [comment]
@nightwing Look at the top of the page https://github.com/c9/c9.ide.run.debug
This is similar in all other plugins. Doesn't come from the Readme.md though, I think it is from the repo title via github.
